trigger:
    - main
    - dev

pool:
    vmImage: "windows-latest"

variables:
    buildConfiguration: "Release"
    appName: "IBBS.AI Build"
    artifactStagingDirectory: "$(Build.SourcesDirectory)/artifacts"

stages:
    - stage: "IBBS_AI_CI"
      jobs:
          - job: API_Build
            steps:
                - task: UseDotNet@2
                  displayName: "Dotnet SDK"
                  inputs:
                      packageType: "sdk"
                      version: "9.0.x"
                      installationPath: $(Agent.ToolsDirectory)/dotnet

                - task: DotNetCoreCLI@2
                  displayName: "Dotnet Restore"
                  inputs:
                      command: "restore"
                      projects: "**/*.csproj"

                - task: SonarCloudPrepare@3
                  displayName: "Prepare Sonarqube analysis"
                  inputs:
                      SonarQube: "IBBS.AI Sonar"
                      organization: "debanjanorg"
                      scannerMode: "dotnet"
                      projectKey: "ibbs-ai"
                      projects: "IBBS.AI.Business/IBBS.AI.Business.csproj"

                - task: DotNetCoreCLI@2
                  displayName: "Dotnet Build"
                  inputs:
                      command: "build"
                      projects: "**/*.csproj"
                      arguments: "--configuration $(buildConfiguration)"

                - task: SonarCloudAnalyze@3
                  displayName: "Run SonarQube Analysis"
                  inputs:
                      jdkversion: "JAVA_HOME_17_X64"
                      projects: "IBBS.AI.Business/IBBS.AI.Business.csproj"

                - task: DotNetCoreCLI@2
                  displayName: "Dotnet Publish"
                  inputs:
                      command: "publish"
                      projects: "**/*.csproj"
                      arguments: "--configuration $(buildConfiguration) --output $(artifactStagingDirectory)"

                - task: PublishBuildArtifacts@1
                  displayName: "Publish Artifacts"
                  inputs:
                      PathToPublish: "$(artifactStagingDirectory)"
                      ArtifactName: "drop"
                      publishLocation: "Container"
