name: Build and Deploy IBBS.AI

env:
    API_PROJECT_PATH: IBBS.AI.API/IBBS.AI.API.csproj

on:
    workflow_dispatch:
        inputs:
            deploy_api:
                description: "IBBS.AI.API"
                required: true
                default: true
                type: boolean

jobs:
    # region API

    build-api:
        name: Build IBBS.AI.API
        runs-on: ubuntu-latest
        outputs:
            artifact-path: ${{ steps.set-artifact-path.outputs.path }}
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up .NET
              uses: actions/setup-dotnet@v3
              with:
                  dotnet-version: "9.0.x"

            - name: Install dependencies and Build solution
              run: |
                  dotnet restore ${{ env.API_PROJECT_PATH }}
                  dotnet build ${{ env.API_PROJECT_PATH }} --configuration Release --no-restore

            - name: Publish the project
              run: |
                  dotnet publish ${{ env.API_PROJECT_PATH }} --configuration Release --no-build --output ./publish-ai-api

            - name: Set artifact path
              id: set-artifact-path
              run: echo "path=./publish-api" >> $GITHUB_OUTPUT

            - name: Upload API Artifact
              uses: actions/upload-artifact@v4
              with:
                  name: api-artifact
                  path: ./publish-ai-api

    deploy-api:
        name: Deploy IBBS.AI.API
        runs-on: ubuntu-latest
        needs: build-api
        if: ${{ inputs.deploy_api }}
        environment: Production
        steps:
            - name: Download API Artifact
              uses: actions/download-artifact@v4
              with:
                  name: api-artifact
                  path: ./publish-ai-api

            - name: Deploy to Azure App Service
              uses: Azure/webapps-deploy@v2
              with:
                  app-name: app-webapi-internet-bulletin-ai
                  slot-name: production
                  publish-profile: ${{ secrets.AZURE_WEBAPI_PUBLISH_PROFILE }}
                  package: ./publish-ai-api
